version: '3.8'
services:
  boilerplate-frontend:
    build:
      context: ./frontend
    container_name: boilerplate-frontend
    restart: unless-stopped
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:      
      - ./frontend/app:/app
    networks:
      - boilerplate

  boilerplate-backend:
    build:
      context: ./backend
    container_name: boilerplate-backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - type: volume
        target: /var/www/html
        read_only: false
    networks:
      - boilerplate
    depends_on:
      - boilerplate-database
    ports:
      - "8001:80"

  boilerplate-database:
    build:
      context: ./database
    container_name: boilerplate-database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - boilerplate

  boilerplate-rabbitmq:
    image: rabbitmq:3.11.0-management-alpine
    container_name: boilerplate-rabbitmq
    tty: true
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/data/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - boilerplate

networks:
  boilerplate:
    name: boilerplate
    driver: bridge
