version: '3.8'
services:
  boilerplate-frontend:
    build:
      context: ./frontend
    container_name: boilerplate-frontend
    restart: unless-stopped
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:      
      - ./frontend/app:/app
    networks:
      - boilerplate

  boilerplate-backend:
    build:
      context: ./backend
    container_name: boilerplate-backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - type: volume
        target: /var/www/html
        read_only: false
    networks:
      - boilerplate
    depends_on:
      - boilerplate-database
    ports:
      - "8001:80"
      - "443:443"
      - "6001:6001"

  boilerplate-database:
    build:
      context: ./database
    container_name: boilerplate-database
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    expose:
      - 3306
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - boilerplate

networks:
  boilerplate:
    name: boilerplate
    driver: bridge
