version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:      
      - ./frontend:/app
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - database
    ports:
      - "8001:80"
      - "443:443"
      - "6001:6001"

  database:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    expose:
      - 3306
    volumes:
      - ./.docker/database/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge